all:
  hosts:
  children:
    routers:
      children:
        cisco_csr:
          vars:
            ansible_user: admin
            ansible_ssh_pass: cisco
            ansible_become_pass: cisco
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            router-1:
              ansible_port: 2201
              ansible_host: REPLACE_ME
            router-2:
              ansible_port: 2202
              ansible_host: REPLACE_ME
            router-3:
              ansible_port: 2203
              ansible_host: REPLACE_ME
    cisco_9k:
      hosts:
        n9kv-4:
          ansible_port: 2204
          ansible_host: REPLACE_ME
      vars:
        ansible_user: admin
        ansible_ssh_pass: cisco
        ansible_become_pass: cisco
        ansible_network_os: nxos
        ansible_connection: network_cli
        ansible_become_method: enable
